original_task = "Less-AnymalC-Flat-Walking-Direct-v1"

train_task = [
    "Less-AnymalC-Rough-Walking-Direct-v1",
    "Less-Leg-Flat-Walking-Direct-v1",
    "Less-Leg-Rough-Walking-Direct-v1",
    "Less-AnymalC-Jump-Direct-v1",
    "Less-AnymalC-Jump-Rough-Direct-v1",
]

model_path = "/home/joonwon/github/less_leg_walking_1.worktrees/origin-master/source/less_leg_walking_1/less_leg_walking_1/tasks/direct/less_leg_walking_1/KAEs/"

